config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/summary'
  get 'kanjis/refresh'
  get 'dashboard/poll'
  get 'vocabularies/refresh'

  devise_for :users
  resources :kanjis, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create, :update]
  resources :sentences, only: [:index, :new, :show, :create, :destroy, :update]
  resources :texts, only: [:index, :new, :show, :create, :destroy, :update]
  resources :vocabularies, only: [:index, :show]

  root "dashboard#summary"

end

app/models/kanji.rb
class Kanji < ActiveRecord::Base

  validates :character, presence: true

  has_many :user_kanji
  has_many :sentence_kanji
  has_many :sentence, :through => :sentence_kanji
end

app/controllers/kanjis_controller.rb
class KanjisController < ApplicationController

  before_action :authenticate_user!

  def index
    if current_user.kanji.length == 0
      if !current_user.apikey
        redirect_to current_user
      end
      current_user.delay.load_kanji
    end
    @user_kanjis = current_user.user_kanji.paginate(:page => params[:page])
  end

  def show
    begin
      @kanji = Kanji.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
    @user_srs = current_user.user_kanji.find_by(:kanji => @kanji)
  end

  def refresh
    if !current_user.apikey
      redirect_to current_user
    end
    current_user.delay.load_kanji
    redirect_to kanjis_path
  end
end

app/views/kanjis/index.html.erb
<div>
  <%= will_paginate @user_kanjis %>
  <ul>
    <% for k in @user_kanjis %>
    <li><%= link_to k.kanji.character, kanji_path(k.kanji) %> - <%= k.srs %> - <%= k.kanji.sentence.count %> Sentences</li>
    <% end %>
  </ul>
  <%= link_to 'Refresh Kanji', kanjis_refresh_path %>
</div>

app/views/kanjis/show.html.erb
<% content_for :title do %>Kanji Details: <%= @kanji.character %><% end %>
<dl>
<dt>Character</dt><dd><%= @kanji.character %></dd>
<dt>SRS Level</dt><dd><%= @user_srs.srs %></dd>
<dt>Meaning</dt><dd><%= @kanji.meaning %></dd>
</dl>

<h4>Sentences</h5>
<ul>
<% for s in @kanji.sentence.shuffle.slice(0,10) %>
<li><%= link_to s.content, s %></li>
<% end %>
</ul>