config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/summary'
  get 'kanjis/refresh'
  get 'dashboard/poll'
  get 'vocabularies/refresh'

  devise_for :users
  resources :kanjis, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create, :update]
  resources :sentences, only: [:index, :new, :show, :create, :destroy, :update]
  resources :texts, only: [:index, :new, :show, :create, :destroy, :update]
  resources :vocabularies, only: [:index, :show]

  root "dashboard#summary"

end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
    
  has_many :user_vocab
  has_many :sentence_vocabulary
  has_many :sentence, :through => :sentence_vocabulary
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController

  before_action :authenticate_user!

  def index
    if current_user.vocabulary.length == 0
      if !current_user.apikey
        redirect_to current_user
      end
      current_user.delay.load_vocab
    end
    @user_vocabs = current_user.user_vocab.paginate(:page => params[:page])
  end

  def show
    begin
      @vocabulary = Vocabulary.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
    @user_srs = current_user.user_vocab.find_by(:vocabulary => @vocabulary)
  end

  def refresh
    if !current_user.apikey
      redirect_to current_user
    end
    current_user.delay.load_vocab
    redirect_to vocabularies_path
  end
end

app/views/vocabularies/index.html.erb
<div>
      <%= will_paginate @user_vocabs %>
      <ul>
        <% for k in @user_vocabs %>
            <li><%= link_to k.vocabulary.character, vocabulary_path(k.vocabulary) %> - <%= k.srs %></li>
        <% end %>
      </ul>
      <%= link_to 'Refresh Vocabs', vocabularies_refresh_path %>
  </div>

app/views/vocabularies/show.html.erb
<% content_for :title do %>Vocab Details: <%= @vocabulary.character %><% end %>
<dl>
    <dt>Character</dt><dd><%= @vocabulary.character %></dd>
    <dt>SRS Level</dt><dd><%= @user_srs.srs %></dd>
    <dt>Meaning</dt><dd><%= @vocabulary.meaning %></dd>
</dl>