config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/summary'
  get 'kanjis/refresh'
  get 'dashboard/poll'
  get 'vocabularies/refresh'

  devise_for :users
  resources :kanjis, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create, :update]
  resources :sentences, only: [:index, :new, :show, :create, :destroy, :update]
  resources :texts, only: [:index, :new, :show, :create, :destroy, :update]
  resources :vocabularies, only: [:index, :show]

  root "dashboard#summary"

end

app/models/text.rb
class Text < ActiveRecord::Base
  has_attached_file :document
  validates_attachment_content_type :document, :content_type => /\Atext\/.*\Z/
  validates :name, presence: true

  belongs_to :user
  has_many :text_sentence
  has_many :sentence, :through => :text_sentence

  after_save :queue_parse, on: [:create]

  def queue_parse
    self.delay.parse
  end

  def parse
    File.open(self.document.path, 'r') do |f|
      while line = f.gets
        line.chomp!
        if line.empty?
          next
        end
        self.sentence.create(:user => self.user, :content => line)
      end
    end
  end

  def length
    self.sentence.inject(0) { |sum, s| sum + s.content.length  }
  end

  def kanji_score
    score = Hash.new(0)
    self.sentence.each do |s|
      ks = s.kanji_score
      if ks
        s.kanji_score.keys.each { |k| score[k] += s.kanji_score.fetch(k, 0) }
      end
    end
    score
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def new
    @text = Text.new
  end

  def index
    @texts = current_user.text
  end

  def create
    @text = current_user.text.new
    text_params = secure_params
    @text.name = text_params[:name]
    if text_params[:content]
      @text.save
      text_params[:content].lines.each do |l|
        @text.sentence.create(:user => current_user, :content => l.chomp)
      end
    else
      @text.document = text_params[:document]
    end
#    @text = current_user.text.create(secure_params)
    if @text.valid?
      flash[:notice] = "Text saved."
      @text.save
    else
      redirect_to :back
    end
    redirect_to texts_path
  end

  def show
    @text = current_user.text.find(params[:id])
  end

  private
  def secure_params
    params.require(:text).permit(:document, :name, :content)
  end
end

app/views/texts/index.html.erb
<ul>
  <% for t in @texts %>
  <li><%= link_to t.name, t %></li>
  <% end %>
</ul>

<p>
  <%= link_to 'Upload...', new_text_path %>
</p>

app/views/texts/new.html.erb
<div class="form">
<%= simple_form_for @text do |form| %>
  <%= form.input :name %>
  <%= form.input :document %>
  <%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>
</div>

app/views/texts/show.html.erb
<div>
  <h3>General Information</h3>
  <dl>
    <dt>Title</dt><dd><%= @text.name %></dd>
    <% if @text.document_file_name %>
    <dt>File</dt><dd><%= link_to @text.document_file_name, @text.document.url %></dd>
    <% end %>
    <dt>Character Count</dt><dd><%= @text.length %></dd>
  </dl>
</div>
<div>
  <h3>Sentences</h3>
  <% for s in @text.sentence %>
  <p><%= link_to s.content, s %></p>
  <% end %>
</div>