config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/summary'
  get 'kanjis/refresh'
  get 'dashboard/poll'
  get 'vocabularies/refresh'

  devise_for :users
  resources :kanjis, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create, :update]
  resources :sentences, only: [:index, :new, :show, :create, :destroy, :update]
  resources :texts, only: [:index, :new, :show, :create, :destroy, :update]
  resources :vocabularies, only: [:index, :show]

  root "dashboard#summary"

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Set Key', user_path(current_user) %></li>
  <li><%= link_to 'Kanji List', kanjis_path %></li>
  <li><%= link_to 'Sentences', sentences_path %></li>
  <li><%= link_to 'Texts', texts_path %></li>
  <li><%= link_to 'Vocabs', vocabularies_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WaniKani Stuff" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wkaniki" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>